// paleta centralizata de culori pentru EasyChef
export default {
  primary: '#2F6444',      
  primaryDark: '#2A4C37',    
  accent: '#008193',         
  background: '#EFFFF5',     
  border: '#000000',
  card: '#FFFFFF',           
  surface: '#EDEDED',        
  current: '#BFBFBF',         
  text: '#4A4A4A',          
  textLight: '#FFFFFF',    
  textDark: '#000000',       
  error: '#FF1B2D',          
  errorDark: '#B8000F',      
  warning: '#D09BBB',        
  success: '#008193',        
  medium: '#e5cb2e',           
  muted: '#B7C9BC',          
  owned: '#31A11D',          
  palepink: '#ffdfe2',        
  rating: '#FFE234',

  bar: '#4A4A4A',
  half: '#ff6500',
  checked: '#a3c1ad',
  partially: '#fff5c1',
  active: '#a4c3ab',
  pinkicon: '#ff939d',
  darkpink: '#bd4b57',
  pinkborder: '#FFB6C1',
  dietaryRedBg: '#FFE5E5',
};
