import { StyleSheet } from 'react-native';
import Colors from './Colors';

export const commonStyles = StyleSheet.create({
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: Colors.primaryDark,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: Colors.text,
    textAlign: 'center',
    marginBottom: 40,
    paddingHorizontal: 24,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.primaryDark,
    marginBottom: 8,
  },
  cardDescription: {
    fontSize: 14,
    color: Colors.text,
    lineHeight: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.text,
    marginBottom: 12,
    marginTop: 20,
  },
  profileName: {
    fontSize: 28,
    fontWeight: 'bold',
    color: Colors.primary,
    marginBottom: 8,
  },
  statNumber: {
    fontSize: 22,
    fontWeight: 'bold',
    color: Colors.primary,
  },
  statLabel: {
    fontSize: 14,
    color: Colors.primary,
    marginTop: 5,
    textAlign: 'center',
  },
  preferenceLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.primaryDark,
    marginBottom: 4,
  },
  preferenceDescription: {
    fontSize: 14,
    color: Colors.text,
  },
  ingredientName: {
    fontSize: 16,
    color: Colors.primaryDark,
  },
  ingredientQuantity: {
    fontSize: 14,
    color: Colors.text,
  },
  ingredientUnit: {
    fontSize: 14,
    color: Colors.text,
    fontStyle: 'italic',
  },
  searchPlaceholder: {
    fontSize: 16,
    color: Colors.border,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.primaryDark,
    marginBottom: 20,
    textAlign: 'center',
  },
  modalLabel: {
    fontSize: 16,
    color: Colors.text,
    marginBottom: 8,
  },

  // carduri
  card: {
    backgroundColor: Colors.card,
    borderRadius: 16,
    padding: 20,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  recipeCard: {
    width: 280,
    height: 350,
    marginTop: 10,
    marginRight: 15,
    backgroundColor: Colors.card,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  recipeImage: {
    width: '100%',
    height: 240,
    resizeMode: 'cover',
  },
  recipeContent: {
    padding: 15,
    paddingBottom: 20,
  },
  recipeName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.primaryDark,
    marginTop: -12,
    marginBottom: 3,
    textAlign: 'center',
  },
  ingredientList: {
    fontSize: 14,
    color: Colors.text,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 5,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.card,
    borderRadius: 12,
    height: 95,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    shadowColor: Colors.border,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    paddingVertical: 0,
    paddingHorizontal: 10,
  },
  menuIconImage: {
    width: 48,
    height: 48,
    marginRight: 12,
    marginLeft: -8,
    resizeMode: 'contain',
  },
  menuText: {
    flex: 1,
  },
  menuTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.text,
    marginBottom: 4,
  },
  menuDescription: {
    fontSize: 14,
    color: Colors.text,
  },
  shoppingListContainer: {
    flex: 1,
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 12,
    padding: 15,
    shadowColor: Colors.border,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 5,
  },
  itemCard: {
    width: '49%',
    height: 30,
    backgroundColor: Colors.surface,
    padding: 6,
    borderRadius: 6,
    marginBottom: 1,
    marginLeft: -4,
    shadowColor: Colors.border,
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 2,
    elevation: 1,
  },
  itemName: {
    fontSize: 16,
    color: Colors.text,
  },
  statCard: {
    backgroundColor: Colors.textLight,
    borderWidth: 1.2,
    borderColor: Colors.border,
    borderRadius: 12,
    paddingVertical: 15,
    paddingHorizontal: 15,
    alignItems: 'center',
    width: '30%',
    shadowColor: Colors.textDark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    flexDirection: 'column',
    justifyContent: 'center',
  },
  statsImage: {
    width: 58,
    height: 58,
    resizeMode: 'contain',
    marginBottom: 6,
  },
  preferenceItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.card,
    padding: 15,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 12,
    marginBottom: 10,
    shadowColor: Colors.border,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  preferenceInfo: {
    flex: 1,
    marginRight: 10,
  },
  ingredientItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.card,
    padding: 15,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 12,
    marginBottom: 10,
    shadowColor: Colors.border,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  ingredientInfo: {
    flex: 1,
    marginRight: 10,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 10,
  },
  searchBarContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 12,
    height: 48,
  },
  searchIcon: {
    width: 36,
    height: 36,
    marginRight: 8,
    resizeMode: 'contain',
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: Colors.text,
    paddingVertical: 8,
  },
  sortButton: {
    backgroundColor: Colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sortIconZoomed: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: Colors.card,
    borderRadius: 16,
    padding: 20,
    width: '90%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalInput: {
    backgroundColor: Colors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 12,
    fontSize: 16,
    color: Colors.text,
    marginBottom: 20,
  },
  measurementTypeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  measurementTypeButton: {
    flex: 1,
    backgroundColor: Colors.surface,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  selectedMeasurementType: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  measurementTypeText: {
    fontSize: 14,
    color: Colors.text,
  },
  selectedMeasurementTypeText: {
    color: Colors.textLight,
    fontWeight: 'bold',
  },


  primaryButton: {
    width: '100%',
    backgroundColor: Colors.primaryDark,
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.primaryDark,
  },
  primaryButtonText: {
    color: Colors.textLight,
    fontSize: 16,
    fontWeight: 'bold',
  },
  secondaryButton: {
    width: '100%',
    backgroundColor: Colors.surface,
    borderColor: Colors.primary,
    borderWidth: 2,
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: 'bold',
  },
  heartButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: Colors.card,
    borderRadius: 30,
    padding: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  quickAccessButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginBottom: 24,
  },
  quickAccessButtonText: {
    color: Colors.textLight,
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  logoutButton: {
    width: '100%',
    backgroundColor: Colors.card,
    borderWidth: 2,
    borderColor: Colors.error,
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
  },
  logoutButtonText: {
    color: Colors.error,
    fontSize: 16,
    fontWeight: 'bold',
  },
  resetButton: {
    backgroundColor: Colors.card,
    padding: 10,
    borderWidth: 2,
    borderColor: Colors.error,
    borderRadius: 12,
    marginTop: 10,
    marginBottom: 10,
    alignItems: 'center',
  },
  resetButtonText: {
    color: Colors.error,
    fontSize: 16,
    fontWeight: 'bold',
  },

  // containere
  screenContainer: {
    flexGrow: 1,
    backgroundColor: Colors.background,
  },
  contentContainer: {
    flex: 1,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: Colors.primaryDark,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  buttonGroup: {
    width: '100%',
    gap: 15,
    marginTop: -20,
  },
  columnWrapper: {
    justifyContent: 'space-between',
    marginBottom: 4.5,
  },
  profileHeader: {
    alignItems: 'center',
    marginBottom: 30,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderColor: Colors.primaryDark,
    borderWidth: 3,
    borderRadius: 60,
    marginBottom: 15,
  },
  statsSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 30,
  },
  listContainer: {
    paddingBottom: 30,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: Colors.primary,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: Colors.primary,
    marginBottom: 20,
  },
}); 