import { StyleSheet } from 'react-native';
import Colors from '../../../constants/Colors';
import { commonStyles } from '../../../constants/Styles';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    padding: 20,
    paddingTop: 50,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.background,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: Colors.primary,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: Colors.primaryDark,
    marginBottom: 10,
    textAlign: 'center',
  },
  ingredientsContainer: {
    marginBottom: 20,
  },
  ingredientSection: {
    backgroundColor: Colors.card,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    shadowColor: Colors.border,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.primaryDark,
    marginBottom: 10,
  },
  ingredientItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  ingredientNameCol: {
    flex: 3,
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 0,
  },
  ingredientQuantityCol: {
    flex: 0.9,
    alignItems: 'center',
    minWidth: 60,
    marginLeft: 50,
  },
  ingredientButtonCol: {
    flex: 0.8,
    alignItems: 'flex-end',
    minWidth: 80,
  },
  ingredientName: {
    fontSize: 16,
    color: Colors.primaryDark,
    fontWeight: '500',
  },
  ingredientQuantity: {
    fontSize: 14,
    color: Colors.text,
    marginTop: 2,
  },
  missingQuantity: {
    color: Colors.half,
  },
  addButtonIcon: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.error,
    marginLeft: 10,
  },
  addedButtonIcon: {
    backgroundColor: Colors.owned,
    borderColor: Colors.owned,
  },
  addAllButton: {
    backgroundColor: Colors.card,
    padding: 12,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: Colors.half,
    alignItems: 'center',
    marginTop: 15,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  addAllButtonText: {
    color: Colors.half,
    fontSize: 16,
    fontWeight: '500',
  },
  startButton: {
    backgroundColor: Colors.primary,
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
  },
  startButtonText: {
    color: Colors.textLight,
    fontSize: 16,
    fontWeight: 'bold',
  },
  offlineBanner: {
    backgroundColor: Colors.error,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  offlineText: {
    color: Colors.textLight,
    marginLeft: 8,
    fontWeight: 'bold',
  },
  imageContainer: {
    position: 'relative',
    marginBottom: 10,
    marginTop: -20,
  },
  image: {
    width: '100%',
    height: 200,
    borderRadius: 12,
  },
  instructionsContainer: {
    marginBottom: 20,
  },
  instruction: {
    fontSize: 16,
    color: Colors.text,
    lineHeight: 24,
    marginBottom: 12,
  },
  conflictingItem: {
    backgroundColor: Colors.background,
  },
  conflictingText: {
    color: Colors.error,
    textDecorationLine: 'underline',
  },
  conflictIcon: {
    marginLeft: 8,
    padding: 4,
  },
  editButtonIcon: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.owned,
    marginLeft: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: 36,
    height: 36,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 24,
    width: 300,
    alignItems: 'stretch',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
    color: Colors.primaryDark,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    padding: 8,
    fontSize: 16,
    marginBottom: 8,
  },
  modalCancelBtn: {
    padding: 10,
    marginRight: 8,
  },
  modalSaveBtn: {
    backgroundColor: Colors.primary,
    padding: 10,
    borderRadius: 8,
  },
  availableIngredient: {
    color: Colors.owned,
  },
  missingIngredient: {
    color: Colors.error,
  },
  conflictingNameBg: {
    backgroundColor: Colors.dietaryRedBg,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  portionsContainer: {
    backgroundColor: Colors.card,
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: Colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  portionsLabel: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.primaryDark,
    marginBottom: 10,
    textAlign: 'center',
  },
  portionsControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 8,
  },
  portionButton: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    minWidth: 45,
    alignItems: 'center',
  },
  activePortionButton: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  portionButtonText: {
    fontSize: 16,
    color: Colors.primaryDark,
    fontWeight: 'bold',
  },
  activePortionButtonText: {
    color: Colors.textLight,
  },
  startButtonDisabled: {
    opacity: 0.7,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 15,
  },
  instructionsCard: {
    backgroundColor: Colors.card,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Colors.border,
    padding: 16,
    marginBottom: 20,
    shadowColor: Colors.border,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  bannedIngredientItem: {
    borderColor: Colors.pinkborder,
    borderRadius: 8,
  },
  bannedIngredientName: {
    color: Colors.darkpink,
    fontWeight: '500',
    backgroundColor: Colors.palepink,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  bannedIngredientQuantity: {
    color: Colors.darkpink,
  },
  bannedButtonIcon: {
    borderColor: Colors.pinkicon,
    backgroundColor: Colors.palepink,
  },
  bannedAvailableIngredientName: {
    textDecorationLine: 'underline',
    textDecorationColor: Colors.darkpink,
    textDecorationStyle: 'solid',
    backgroundColor: Colors.palepink,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    color: Colors.darkpink,
  },
  instructionsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  expandButton: {
    width: '38%',
    marginTop: -8,
    backgroundColor: Colors.card,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  expandButtonText: {
    color: Colors.primaryDark,
    fontWeight: 'bold',
    fontSize: 14,
    textAlign: 'center',
  },
  previewText: {
    color: Colors.border,
    fontStyle: 'italic',
    fontSize: 14,
  },
  sourceButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.card,
    padding: 12,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  sourceButtonText: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  areaBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: Colors.card,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
    zIndex: 2,
    alignSelf: 'flex-start',
  },
  areaBadgeText: {
    color: Colors.primary,
    fontSize: 12,
    fontWeight: 'bold',
    textTransform: 'capitalize',
  },
}); 

export default styles;