import { StyleSheet } from 'react-native';
import Colors from '../../../constants/Colors';
import { commonStyles } from '../../../constants/Styles';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    content: {
      flex: 1,
      padding: 20,
      paddingTop: 20,
    },
    title: {
      fontSize: 28,
      fontWeight: 'bold',
      color: Colors.primaryDark,
      marginBottom: 20,
      textAlign: 'center',
    },
    listContainer: {
      paddingBottom: 30,
    },
    ingredientItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: Colors.card,
      padding: 15,
      borderWidth: 1,
      borderColor: Colors.border,
      borderRadius: 18,
      marginBottom: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 3,
    },
    ingredientInfo: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
    },
    ingredientName: {
      fontSize: 16,
      color: Colors.text,
    },
    rightActions: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      minWidth: 90,
    },
    quantitySquareBadge: {
      backgroundColor: Colors.surface,
      borderRadius: 5,
      paddingHorizontal: 0,
      paddingVertical: 6,
      marginRight: 8,
      minWidth: 60,
      maxWidth: 60,
      width: 60,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
    },
    quantitySquareBadgeText: {
      color: Colors.primary,
      fontWeight: 'bold',
      fontSize: 15,
      textAlign: 'center',
      letterSpacing: 1,
    },
    removeButton: {
      padding: 8,
      borderWidth: 0,
      borderColor: Colors.error,
      borderRadius: 5,
      backgroundColor: Colors.palepink,
      marginLeft: 0,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      fontSize: 16,
      color: Colors.primary,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    emptyText: {
      fontSize: 16,
      color: Colors.primary,
      marginBottom: 20,
    },
    addButton: {
      backgroundColor: Colors.primary,
      padding: 10,
      borderRadius: 12,
      marginTop: 10,
      
    },
    addButtonText: {
      color: Colors.textLight,
      fontSize: 16,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
      backgroundColor: Colors.surface,
      borderRadius: 12,
      padding: 20,
      width: '80%',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: Colors.primaryDark,
      marginBottom: 15,
      textAlign: 'center',
    },
    modalSubtitle: {
      fontSize: 16,
      color: Colors.primary,
      marginBottom: 20,
      textAlign: 'center',
    },
    quantityInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
    },
    quantityInput: {
      backgroundColor: Colors.surface,
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      borderWidth: 1,
      borderColor: Colors.border,
      minWidth: 90,
    },
    unitText: {
      fontSize: 16,
      color: Colors.primaryDark,
      fontWeight: '500',
      marginLeft: 8,
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    modalButton: {
      flex: 1,
      padding: 12,
      borderRadius: 8,
      marginHorizontal: 5,
    },
    cancelButton: {
      backgroundColor: Colors.surface,
    },
    confirmButton: {
      backgroundColor: Colors.primary,
    },
    buttonText: {
      fontSize: 16,
      fontWeight: 'bold',
      textAlign: 'center',
      color: Colors.primaryDark,
    },
    confirmButtonText: {
      color: Colors.textLight,
    },
    measurementTypeContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginBottom: 15,
    },
    measurementTypeButton: {
      backgroundColor: Colors.surface,
      padding: 8,
      borderRadius: 8,
      marginBottom: 8,
      width: '48%',
      alignItems: 'center',
    },
    selectedMeasurementType: {
      backgroundColor: Colors.primary,
    },
    measurementTypeText: {
      fontSize: 14,
      color: Colors.primaryDark,
    },
    selectedMeasurementTypeText: {
      color: Colors.textLight,
      fontWeight: 'bold',
    },
    weightText: {
      color: Colors.primary,
    },
    otherText: {
      color: Colors.text,
      fontStyle: 'italic',
    },
    deleteAllButtonBottom: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: Colors.card,
      padding: 12,
      borderWidth: 2,
      borderColor: Colors.error,
      borderRadius: 12,
      marginTop: 10,
      marginBottom: -5,
    },
    deleteAllButtonBottomText: {
      color: Colors.error,
      marginLeft: 8,
      fontWeight: 'bold',
      fontSize: 16,
    },
    headerContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    sortButton: {
      width: 45,
      height: 45,
      borderWidth: 1,
      borderColor: Colors.border,
      borderRadius: 12,
      backgroundColor: Colors.card,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    sortIconContainer: {
      width: 45,
      height: 45,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    sortIconZoomed: {
      width: 36,
      height: 36,
      resizeMode: 'contain',
    },
    searchAndSortContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 20,
      gap: 10,
    },
    searchBarContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: Colors.border,
      paddingHorizontal: 15,
      flex: 1,
    },
    searchIcon: {
      width: 36,
      height: 36,
      marginRight: 10,
    },
    searchBar: {
      flex: 1,
      paddingVertical: 12,
      fontSize: 16,
      color: Colors.text,
    },
  });

  export default styles;