import { StyleSheet } from 'react-native';
import Colors from '../../../constants/Colors';
import { commonStyles } from '../../../constants/Styles';


export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    content: {
      flex: 1,
      padding: 20,
      paddingTop: 20,
    },
    headerContainer: {
      alignItems: 'center',
      marginBottom: 20,
      marginTop: -20,
    },
    title: {
      fontSize: 28,
      fontWeight: 'bold',
      color: Colors.primaryDark,
      marginBottom: 10, 
      textAlign: 'center',
    },
    itemCountText: {
      fontSize: 18,
      color: Colors.text,
      textAlign: 'center',
    },
    searchSortRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
      gap: 10,
    },
    searchBarContainer: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: Colors.border,
      paddingHorizontal: 12,
      height: 48,
    },
    searchIcon: {
      width: 36,
      height: 36,
      marginRight: 8,
      resizeMode: 'contain',
    },
    searchInput: {
      flex: 1,
      fontSize: 16,
      color: Colors.text,
      paddingVertical: 8,
    },
    sortButton: {
      backgroundColor: Colors.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: Colors.border,
      width: 48,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sortIconZoomed: {
      width: 32,
      height: 32,
      resizeMode: 'contain',
    },
    sortingInfoContainer: {
      backgroundColor: Colors.background,
      padding: 8,
      borderRadius: 12,
      marginBottom: 16,
      borderWidth: 0,
      borderColor: Colors.border,
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
    },
    sortingInfoText: {
      fontSize: 15,
      color: Colors.primaryDark,
      fontWeight: '600',
    },
    listContainer: {
      paddingBottom: 30,
    },
    categoryContainer: {
      marginBottom: 20,
    },
    categoryTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: Colors.primaryDark,
      marginBottom: 10,
      paddingHorizontal: 5,
    },
    itemContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.palepink,
      padding: 12,
      height: 50,
      borderWidth: 1,
      borderColor: Colors.error,
      borderRadius: 12,
      marginBottom: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    checkedItemContainer: {
      borderWidth: 1,
      borderColor: Colors.border,
      backgroundColor: Colors.checked,
    },
    checkbox: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: Colors.border,
      marginRight: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    checkboxText: {
      color: Colors.primary,
      fontSize: 16,
      fontWeight: 'bold',
    },
    itemDetails: {
      flex: 1,
    },
    itemName: {
      fontSize: 16,
      color: Colors.primaryDark,
    },
    checkedItem: {
      textDecorationLine: 'line-through',
      color: Colors.border,
    },
    quantityText: {
      color: Colors.error,
      fontSize: 16,
      //fontWeight: 'bold',
    },
    removeButton: {
      padding: 8,
      marginLeft: 8,
      borderRadius: 8,
      backgroundColor: Colors.surface,
      borderWidth: 1,
      borderColor: Colors.error,
      width: 36,
      height: 36,
      justifyContent: 'center',
      alignItems: 'center',
    },
    removeButtonText: {
      color: Colors.error,
      fontSize: 16,
      fontWeight: 'bold',
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    emptyText: {
      fontSize: 18,
      color: Colors.border,
      textAlign: 'center',
    },
    clearButton: {
      backgroundColor: Colors.card,
      borderWidth: 2,
      borderColor: Colors.error,
      padding: 12,
      borderRadius: 12,
      marginTop: 20,
      alignItems: 'center',
    },
    clearButtonText: {
      color: Colors.error,
      fontSize: 16,
      fontWeight: 'bold',
    },
    recipeText: {
      fontSize: 12,
      color: Colors.text,
      fontStyle: 'italic',
    },
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
      backgroundColor: Colors.surface,
      borderRadius: 12,
      padding: 20,
      width: '80%',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: Colors.primaryDark,
      marginBottom: 15,
      textAlign: 'center',
    },
    quantityInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
    },
    quantityInput: {
      backgroundColor: Colors.surface,
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      borderWidth: 1,
      borderColor: Colors.border,
      marginRight: 8,
    },
    unitText: {
      fontSize: 16,
      color: Colors.primaryDark,
      fontWeight: '500',
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    modalButton: {
      flex: 1,
      padding: 12,
      borderRadius: 8,
      marginHorizontal: 5,
    },
    cancelButton: {
      backgroundColor: Colors.surface,
    },
    confirmButton: {
      backgroundColor: Colors.primary,
    },
    buttonText: {
      fontSize: 16,
      fontWeight: 'bold',
      textAlign: 'center',
      color: Colors.primaryDark,
    },
    confirmButtonText: {
      color: Colors.textLight,
    },
    pantryInfoBox: {
      backgroundColor: Colors.surface,
      borderRadius: 6,
      padding: 6,
      paddingRight: 12,
      marginTop: 0,
      marginBottom: 2,
      flexWrap: 'wrap',
      flexDirection: 'row',
    },
    pantryInfoText: {
      color: Colors.primary,
      fontSize: 13,
      fontStyle: 'italic',
      flexShrink: 1,
    },
    remainingQuantityText: {
      color: Colors.error,
      fontSize: 13,
      fontStyle: 'italic',
    },
    warningIcon: {
      marginLeft: 4,
    },
  });

  export default styles;