import { StyleSheet } from 'react-native';
import Colors from '../../../constants/Colors';
import { commonStyles } from '../../../constants/Styles';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    header: {
      padding: 18,
      backgroundColor: Colors.primary,
      alignItems: 'center',
      marginBottom: 0,
    },
    headerTop: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 6,
    },
    title: {
      fontSize: 28,
      fontWeight: 'bold',
      color: Colors.textLight,
      marginBottom: 4,
      textAlign: 'center',
    },
    subtitle: {
      fontSize: 16,
      color: Colors.textLight,
      opacity: 0.85,
    },
    daysScroll: {
      flexGrow: 0,
      backgroundColor: Colors.surface,
      paddingVertical: 16,
    },
    daysScrollContent: {
      flexGrow: 1,
    },
    dayCard: {
      backgroundColor: Colors.card,
      height: 400,
      borderRadius: 10,
      padding: 16,
      elevation: 4,
      shadowColor: Colors.border,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.10,
      shadowRadius: 8,
      alignItems: 'center',
    },
    dayHeaderContainer: {
      alignItems: 'center',
      marginBottom: 6,
    },
    dayHeader: {
      fontSize: 20,
      fontWeight: 'bold',
      color: Colors.primaryDark,
      letterSpacing: 1,
    },
    dayDate: {
      fontSize: 14,
      color: Colors.primary,
      marginTop: 2,
    },
    selectedDayCard: {
      borderWidth: 3,
      borderColor: Colors.owned,
      shadowColor: Colors.accent,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 6,
    },
    mealSlotContainer: {
      backgroundColor: Colors.surface,
      borderRadius: 8,
      borderColor: Colors.border,
      borderWidth: 0,
      marginBottom: 12,
      padding: 8,
      width: 260,
      minHeight: 80,
      shadowColor: Colors.border,
      shadowOffset: { width: 0, height: 0.5 },
      shadowOpacity: 0.05,
      shadowRadius: 3,
      elevation: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    mealEmojiContainer: {
      position: 'absolute',
      top: -14,
      left: 0,
      zIndex: 1,
    },
    mealEmojiSmall: {
      fontSize: 18,
    },
    mealEmojiImage: {
      width: 30,
      height: 30,
      resizeMode: 'contain',
      borderColor: Colors.border,
      borderWidth: 0.8,
      borderRadius: 15,
    },
    mealContentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    mealImageRectWrapperSmall: {
      width: 50,
      height: 50,
      borderColor: Colors.border,
      borderWidth: 1,
      borderRadius: 8,
      overflow: 'hidden',
      backgroundColor: Colors.surface,
      marginTop: 3,
      marginRight: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    mealImageRectSmall: {
      width: 50,  //poza reteta
      height: 50,
      borderRadius: 8,
    },
    mealTitleRectWrapperNew: {
      flex: 1,
      justifyContent: 'center',
    },
    mealTitleRectNew: {
      fontSize: 17,
      fontWeight: 'bold',
      color: Colors.primaryDark,
      textAlign: 'left',
      lineHeight: 20,
    },
    mealActionsRectStacked: {
      flexDirection: 'column',
      alignItems: 'center',
      marginLeft: 8,
      gap: 4,
    },
    actionButtonRectSmall: {
      width: 32,
      height: 32,
      padding: 3,
      backgroundColor: Colors.card,
      borderRadius: 8,
      borderWidth: 0,
      borderColor: Colors.primary,
      alignItems: 'center',
    },
    addMealButtonCentered: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 10,
      backgroundColor: 'transparent',
      borderRadius: 8,
    },
    calendarButton: {
      backgroundColor: Colors.primary,
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 20,
      marginTop: 16,
      alignItems: 'center',
      width: '100%',
    },
    calendarButtonText: {
      color: Colors.textLight,
      fontSize: 16,
      fontWeight: 'bold',
    },
    dateViewContainer: {
      flex: 1,
      backgroundColor: Colors.surface,
    },
    dateHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      backgroundColor: Colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: Colors.border,
    },
    backButton: {
      marginRight: 16,
    },
    dateTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: Colors.primary,
    },
    dateMealsContainer: {
      padding: 16,
     
    },
    plannedPercentageContainer: {
      padding: 16,
      backgroundColor: Colors.surface,
      borderTopWidth: 1,
      borderTopColor: Colors.border,
    },
    plannedPercentageText: {
      fontSize: 18,
      marginTop: -7,
      fontWeight: 'bold',
      color: Colors.primary,
      textAlign: 'center'
    },
    progressBarContainer: {
      height: 22,
      width: '90%',
      backgroundColor: Colors.background,
      borderRadius: 8,
      marginTop: 8,
      overflow: 'hidden',
      alignSelf: 'center',
      borderColor: Colors.border,
      borderWidth: 2,
    },
    progressBarFill: {
      height: '100%',
      backgroundColor: Colors.primary,
      borderRadius: 5,
    },
    planningSummaryContainer: {
      padding: 20,
      backgroundColor: Colors.background,
    },
    mealSlot: {
      backgroundColor: Colors.surface,
      borderRadius: 8,
      marginBottom: 12,
      padding: 8,
      width: 210,
      minHeight: 60,
      shadowColor: Colors.border,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    mealHeader: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    mealType: {
      fontSize: 18,
      fontWeight: 'bold',
      color: Colors.primaryDark,
    },
    mealActions: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    actionIcon: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 0,
      borderColor: Colors.border,
      resizeMode: 'contain',
      
    },
    mealContent: {
      flex: 1,
    },
    mealTitle: {
      fontSize: 15,
      fontWeight: 'bold',
      color: Colors.primaryDark,
      textAlign: 'left',
      lineHeight: 18,
    },
    mealDescription: {
      fontSize: 14,
      color: Colors.primary,
      textAlign: 'left',
      lineHeight: 18,
    },
    emptyMealText: {
      fontSize: 14,
      color: Colors.primary,
      textAlign: 'left',
      lineHeight: 18,
    },
    progressContainer: {
      marginBottom: 0,
      marginTop: -8,
      paddingHorizontal: 20,
      backgroundColor: Colors.surface,
      paddingVertical: 8, 
    },
    deleteAllButton: {
      width: 220,
      alignSelf: 'center',
      backgroundColor: Colors.card,
      paddingVertical: 12, 
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: Colors.error,
      alignItems: 'center',
      shadowColor: Colors.border,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
      marginTop: 0, 
      marginBottom: 0, 
    },
    deleteAllButtonText: {
      color: Colors.error,
      fontSize: 16,
      fontWeight: 'bold',
    },
    overlayLoader: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(255,255,255,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 100,
    },
    pastMealSlot: {
      opacity: 0.7,
      backgroundColor: Colors.surface,
    },
    pastMealTitle: {
      color: Colors.bar,
    },
  }); 

  export default styles;